teste/src/main/java/br/com/hemocloud/usuario/UsuarioBean.java
package br.com.hemocloud.usuario;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

import org.hibernate.StaleObjectStateException;

@ManagedBean(name="usuarioBean")
@RequestScoped
public class UsuarioBean {
	
	private Usuario usuario = new Usuario();
	private String confirmaSenha;
	private List<Usuario> lista;
	private String destinosalvar;
	private boolean somentePesquisa;
	private boolean isAdministrador;
	
	public String novo() {
		this.destinosalvar = "/publico/mostrausuario";
		this.usuario = new Usuario();
		this.usuario.setAtivo(true);
		return "usuario";
	}
	
	public String editar() {
		this.confirmaSenha = this.usuario.getSenha();
		this.isAdministrador = this.usuario.getPermissao().contains("ROLE_ADMINISTRADOR");
		this.setSomentePesquisa(false);
		return "usuario";
	}
	
	public String visualizar() {
		this.confirmaSenha = this.usuario.getSenha();
		this.isAdministrador = this.usuario.getPermissao().contains("ROLE_ADMINISTRADOR");
		this.setSomentePesquisa(true);
		return "usuario";
	}
	
	public String salvar() {
		FacesContext context = FacesContext.getCurrentInstance();
		String senha = this.usuario.getSenha();
		if (!senha.equals(this.confirmaSenha)) {
			context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,
					"Senha confirmada incorretamente!",""));
			return "index";
		}
		if (this.usuario.getCodigo() == null || this.usuario.getCodigo() == 0) {
			this.usuario.setAtivo(true);
		}
		java.util.Set<String> permissoes = this.usuario.getPermissao();
		if (isAdministrador) {
			permissoes.add("ROLE_ADMINISTRADOR");
		} else {
			permissoes.remove("ROLE_ADMINISTRADOR");
		}
		UsuarioRN usuarioRN = new UsuarioRN();
		try {
			usuarioRN.salvar(this.usuario);
		} catch (StaleObjectStateException e) {
			context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN,
					"Alteração recusada! Registro alterado por outro usuário!",""));
		}
		
		return this.destinosalvar;
	}
	
	public String excluir() {
		UsuarioRN usuarioRN = new UsuarioRN();
		usuarioRN.excluir(this.usuario);
		this.lista = null;
		return null;
	}
	
	public String ativar() {
		this.usuario.setAtivo(this.usuario.isAtivo() ? false : true);
		UsuarioRN usuarioRN = new UsuarioRN();
		usuarioRN.salvar(this.usuario);
		return null;
	}
	
	public void gerar() {
		Calendar calendar = Calendar.getInstance();
		SimpleDateFormat simpledateformat = new SimpleDateFormat("DDMMYYYY_HHMMSS_");
		HttpServletRequest request = (HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
		Integer quantidadeUsuarios = Integer.parseInt(request.getParameter("quantidadeUsuarios"));
		if (quantidadeUsuarios != 0 || quantidadeUsuarios != null) {
			UsuarioRN usuarioRN = new UsuarioRN();
			for (int i = 0; i < quantidadeUsuarios; i++) {
				this.usuario = new Usuario();
				this.usuario.setNome("TesteGerador_" + simpledateformat.format(calendar.getTime()) + String.valueOf(i));
				this.usuario.setEmail("TesteGerador_" + simpledateformat.format(calendar.getTime()) + String.valueOf(i) + "@gerador.com");
				this.usuario.setSenha("TesteGerador_" + simpledateformat.format(calendar.getTime()) + String.valueOf(i));
				this.usuario.setAtivo(true);
				usuarioRN.salvar(this.usuario);
			}
		}
	}
	
	public List<Usuario> getLista() {
		if (this.lista == null) {
			UsuarioRN usuarioRN = new UsuarioRN();
			this.lista = usuarioRN.listar();
		}
		return this.lista;
	}
	
	public String atribuiPermissao(Usuario usuario, String permissao) {
		this.usuario = usuario;
		java.util.Set<String> permissoes = this.usuario.getPermissao();
		if (permissoes.contains(permissao)) {
			permissoes.remove(permissao);
		} else {
			permissoes.add(permissao);
		}
		return null;
	}

	public boolean isAdministrador() {
		return isAdministrador;
	}

	public void setAdministrador(boolean isAdministrador) {
		this.isAdministrador = isAdministrador;
	}

	public Usuario getUsuario() {
		return usuario;
	}
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	public String getConfirmasenha() {
		return confirmaSenha;
	}
	public void setConfirmasenha(String confirmasenha) {
		this.confirmaSenha = confirmasenha;
	}

	public String getDestinosalvar() {
		return destinosalvar;
	}

	public void setDestinosalvar(String destinosalvar) {
		this.destinosalvar = destinosalvar;
	}

	public boolean isSomentePesquisa() {
		return somentePesquisa;
	}

	public void setSomentePesquisa(boolean somentePesquisa) {
		this.somentePesquisa = somentePesquisa;
	}
	
}

teste/src/main/webapp/admin/gerador.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:sec="http://www.springframework.org/security/facelets/tags">
<h:head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<!-- Bootstrap -->
	<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
	<h:outputStylesheet library="css" name="font-awesome.css"></h:outputStylesheet>
	<h:outputStylesheet library="css" name="callout.css"></h:outputStylesheet>
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>HemoCloud - Gerador de Registros</title>


	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</h:head>
<h:body>
	<!-- Header -->
	<div id="top-nav" class="navbar navbar-inverse navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-toggle"></span>
				</button>
				<a class="navbar-brand" href="#"><i class="fa fa-cloud"></i>
					HemoCloud</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">

					<li class="dropdown"><a class="dropdown-toggle" role="button"
						data-toggle="dropdown" href="#"> <i
							class="glyphicon glyphicon-user"></i> <h:outputText
								value=" #{request.userPrincipal.name}" /> <span class="caret"></span></a>
						<ul id="g-account-menu" class="dropdown-menu" role="menu">
							<li><a href="#">My Profile</a></li>
							<li><a
								href="#{request.contextPath}/j_spring_security_logout"><i
									class="glyphicon glyphicon-lock"></i> Logout</a></li>
						</ul></li>
				</ul>
			</div>
		</div>
		<!-- /container -->
	</div>
	<!-- /Header -->

	<!-- Main -->
	<div class="container">

		<!-- upper section -->
		<div class="row">
			<div class="col-sm-3">
				<!-- left -->
				<h3>
					<i class="glyphicon glyphicon-briefcase"></i> Toolbox
				</h3>
				<hr />

				<ul class="nav nav-stacked">
					<li class="active"><a href="../restrito/dashboard.jsf"><i
							class="glyphicon glyphicon-dashboard"></i> Painel do Usuário</a></li>
					<li class="active"><a href="usuarios.jsf"><i
							class="fa fa-users"></i> Usuários</a></li>
					<li class="active"><a href="gerador.jsf"><i
							class="fa fa-random"></i> Gerar Registros</a></li>
				</ul>

				<hr />

			</div>
			<!-- /span-3 -->
			<div class="col-sm-9">

				<!-- column 2 -->
				<h3>
					<i class="fa fa-random"></i> Gerar Registros
				</h3>

				<hr />
				<div class="row">
					<h:form>

						<div class="panel panel-primary">
							<div class="panel-heading" role="tab" id="dadosPessoais">
								<div class="panel-title">
									<i class="fa fa-users"></i> Gerar Usuários <a role="button"
										data-toggle="collapse" data-parent="#accordion"
										href="#collapseOne" aria-expanded="true"
										aria-controls="collapseOne"> <i
										class="glyphicon glyphicon-chevron-down pull-right"></i>
									</a>
								</div>
							</div>
							<div id="collapseOne" class="panel-collapse collapse in"
								role="tabpanel" aria-labelledby="dadosPessoais">
								<div class="panel-body">
									<div class="col-lg-12">
										<div class="input-group">
											<input type="text" class="form-control"
												id="quantidadeUsuarios" name="quantidadeUsuarios"
												placeholder="Quantidade de Usuários..." /> <span
												class="input-group-btn"> <h:commandButton
													action="#{usuarioBean.gerar}" class="btn btn-success"
													value="Gerar" />
											</span>
										</div>
										<!-- /input-group -->
									</div>
									<!-- /.col-lg-6 -->
								</div>
							</div>
						</div>
					</h:form>
				</div>
				<div class="row">
					<h:form>

						<div class="panel panel-primary">
							<div class="panel-heading" role="tab" id="dadosPessoais">
								<div class="panel-title">
									<i class="fa fa-users"></i> Gerar Pacientes <a role="button"
										data-toggle="collapse" data-parent="#accordion"
										href="#collapseTwo" aria-expanded="true"
										aria-controls="#collapseTwo"> <i
										class="glyphicon glyphicon-chevron-down pull-right"></i>
									</a>
								</div>
							</div>
							<div id="collapseTwo" class="panel-collapse collapse in"
								role="tabpanel" aria-labelledby="dadosPessoais">
								<div class="panel-body">
									<div class="col-lg-12">
										<div class="input-group">
											<input type="text" class="form-control"
												id="quantidadePacientes" name="quantidadePacientes"
												placeholder="Quantidade de Pacientes..." /> <span
												class="input-group-btn"> <h:commandButton
													action="#{pacienteBean.gerar}" class="btn btn-success"
													value="Gerar" />
											</span>
										</div>
										<!-- /input-group -->
									</div>
									<!-- /.col-lg-6 -->
								</div>
							</div>
						</div>
					</h:form>
				</div>
				<div class="row">
					<h:form>

						<div class="panel panel-primary">
							<div class="panel-heading" role="tab" id="dadosPessoais">
								<div class="panel-title">
									<i class="glyphicon glyphicon-list-alt"></i> Gerar Triagens <a
										role="button" data-toggle="collapse" data-parent="#accordion"
										href="#collapseThree" aria-expanded="true"
										aria-controls="#collapseThree"> <i
										class="glyphicon glyphicon-chevron-down pull-right"></i>
									</a>
								</div>
							</div>
							<div id="collapseThree" class="panel-collapse collapse in"
								role="tabpanel" aria-labelledby="dadosPessoais">
								<div class="panel-body">
									<div class="col-lg-12">
										<div class="input-group">
											<input type="text" class="form-control"
												id="quantidadeTriagens" name="quantidadeTriagens"
												placeholder="Quantidade de Triagens..." /> <span
												class="input-group-btn"> <h:commandButton
													action="#{triagemBean.gerar}" class="btn btn-success"
													value="Gerar" />
											</span>
										</div>
										<!-- /input-group -->
									</div>
									<!-- /.col-lg-6 -->
								</div>
							</div>
						</div>
					</h:form>
				</div>
			</div>
			<!--/col-span-9-->

		</div>
		<!--/row-->
		<!-- /upper section -->
		<footer>
		<p>
			<i class="fa fa-copyright"></i> Guilherme Scha Vieira - 2015
		</p>
		</footer>

	</div>
	<!--/container-->
	<!-- /Main -->

	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="../resources/js/bootstrap.min.js"></script>
</h:body>
</html>

teste/src/main/webapp/admin/principal.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:sec="http://www.springframework.org/security/facelets/tags">
<h:head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<!-- Bootstrap -->
	<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
	<h:outputStylesheet library="css" name="font-awesome.css"></h:outputStylesheet>
	<h:outputStylesheet library="css" name="callout.css"></h:outputStylesheet>
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>HemoCloud - Painel do Usuário</title>


	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</h:head>
<h:body>
	<!-- Header -->
	<div id="top-nav" class="navbar navbar-inverse navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-toggle"></span>
				</button>
				<a class="navbar-brand" href="#"><i class="fa fa-cloud"></i> HemoCloud</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">

					<li class="dropdown"><a class="dropdown-toggle" role="button"
						data-toggle="dropdown" href="#"> <i
							class="glyphicon glyphicon-user"></i> <h:outputText value=" #{request.userPrincipal.name}"/> <span class="caret"></span></a>
						<ul id="g-account-menu" class="dropdown-menu" role="menu">
							<li><a href="#">My Profile</a></li>
							<li><a href="#{request.contextPath}/j_spring_security_logout"><i class="glyphicon glyphicon-lock"></i>
									Logout</a></li>
						</ul></li>
				</ul>
			</div>
		</div>
		<!-- /container -->
	</div>
	<!-- /Header -->

	<!-- Main -->
	<div class="container">

		<!-- upper section -->
		<div class="row">
			<div class="col-sm-3">
				<!-- left -->
				<h3>
					<i class="glyphicon glyphicon-briefcase"></i> Toolbox
				</h3>
				<hr />

				<ul class="nav nav-stacked">
					<li class="active"><a href="../restrito/dashboard.jsf"><i
							class="glyphicon glyphicon-dashboard"></i> Painel do Usuário</a></li>
					<li class="active"><a href="usuarios.jsf"><i class="fa fa-users"></i>
							Usuários</a></li>
					<li class="active"><a href="gerador.jsf"><i class="fa fa-random"></i>
							Gerar Registros</a></li>
				</ul>

				<hr />

			</div>
			<!-- /span-3 -->
			<div class="col-sm-9">

				<!-- column 2 -->
				<h3>
					<i class="fa fa-shield"></i> Área Administrativa
				</h3>

				<hr />
            <div class="row">
                <div class="col-lg-12 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-comments fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">26</div>
                                    <div>New Comments!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
				<div class="row">
                <div class="col-lg-12 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-tasks fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">12</div>
                                    <div>New Tasks!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
				<div class="row">
                <div class="col-lg-12 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-shopping-cart fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">124</div>
                                    <div>New Orders!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
				<div class="row">
                <div class="col-lg-12 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-support fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">13</div>
                                    <div>Support Tickets!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
				<div class="row">

						<div id="alertCadastroPaciente"
							class="alert alert-success collapse" role="alert">
							<button type="button" class="close" data-dismiss="alert"
								aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
							Paciente cadastrado com sucesso.
						</div>
					<!--center-right-->
					<div class="col-md-12">
					</div>
					<!--/col-span-6-->



				</div>
				<!--/row-->
			</div>
			<!--/col-span-9-->

		</div>
		<!--/row-->
		<!-- /upper section -->
		<footer><p><i class="fa fa-copyright"></i> Guilherme Scha Vieira - 2015</p></footer>

	</div>
	<!--/container-->
	<!-- /Main -->

	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="../resources/js/bootstrap.min.js"></script>
</h:body>
</html>

teste/src/main/webapp/admin/usuario.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:sec="http://www.springframework.org/security/facelets/tags">
<h:head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<!-- Bootstrap -->
	<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
	<h:outputStylesheet library="css" name="font-awesome.css"></h:outputStylesheet>
	<h:outputStylesheet library="css" name="callout.css"></h:outputStylesheet>
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>HemoCloud - Painel do Usuário</title>


	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</h:head>
<h:body>
	<!-- Header -->
	<div id="top-nav" class="navbar navbar-inverse navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-toggle"></span>
				</button>
				<a class="navbar-brand" href="#"><i class="fa fa-cloud"></i>
					HemoCloud</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">

					<li class="dropdown"><a class="dropdown-toggle" role="button"
						data-toggle="dropdown" href="#"> <i
							class="glyphicon glyphicon-user"></i> <h:outputText
								value=" #{request.userPrincipal.name}" /> <span class="caret"></span></a>
						<ul id="g-account-menu" class="dropdown-menu" role="menu">
							<li><a href="#">My Profile</a></li>
							<li><a
								href="#{request.contextPath}/j_spring_security_logout"><i
									class="glyphicon glyphicon-lock"></i> Logout</a></li>
						</ul></li>
				</ul>
			</div>
		</div>
		<!-- /container -->
	</div>
	<!-- /Header -->

	<!-- Main -->
	<div class="container">

		<!-- upper section -->
		<div class="row">
			<div class="col-sm-3">
				<!-- left -->
				<h3>
					<i class="fa fa-shield"></i> Área Administrativa
				</h3>
				<hr />

				<ul class="nav nav-stacked">
					<li class="active"><a href="../restrito/dashboard.jsf"><i
							class="glyphicon glyphicon-dashboard"></i> Dashboard</a></li>
					<li class="active"><a href="usuarios.jsf"><i
							class="fa fa-users"></i> Usuários</a></li>
					<li class="active"><a href="gerador.jsf"><i
							class="fa fa-random"></i> Gerar Registros</a></li>
				</ul>

				<hr />

			</div>
			<!-- /span-3 -->
			<div class="col-sm-9">

				<div class="row">
					<div class="col-md-3">
						<!-- column 2 -->
						<h2>
							<i class="fa fa-users"></i> Usuário
						</h2>
					</div>
				</div>


				<hr />

				<div class="row">
					<!--center-right-->
					<div class="col-md-12">
						<div id="alertCadastroPaciente"
							class="alert alert-success collapse" role="alert">
							<button type="button" class="close" data-dismiss="alert"
								aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
							Paciente cadastrado com sucesso.
						</div>

						<h:form>

							<div class="panel panel-success">
								<div class="panel-heading">
									<div class="panel-title">
										<i class="glyphicon glyphicon-wrench pull-right"></i>
										<h4>Dados do usuário</h4>
									</div>
								</div>
								<div class="panel-body">

									<h:form class="form form-vertical" role="form">
										<h:inputHidden value="#{usuarioBean.usuario.codigo}" />
										<h:inputHidden value="#{usuarioBean.usuario.version}" />
										<div class="control-group">
											<label>Nome</label>
											<div class="controls">
												<h:inputText type="text" value="#{usuarioBean.usuario.nome}"
													readonly="#{usuarioBean.somentePesquisa}"
													class="form-control" id="inputNome" />
											</div>
										</div>
										<div class="control-group">
											<label>Email</label>
											<div class="controls">
												<h:inputText type="email"
													value="#{usuarioBean.usuario.email}"
													readonly="#{usuarioBean.somentePesquisa}"
													class="form-control" id="inputEmail1" />
											</div>
										</div>
										<div class="control-group">
											<label>Senha</label>
											<div class="controls">
												<h:inputText type="email"
													value="#{usuarioBean.usuario.senha}"
													readonly="#{usuarioBean.somentePesquisa}"
													class="form-control" id="inputSenha1" />
											</div>
										</div>
										<div class="control-group">
											<label>Confirma Senha</label>
											<div class="controls">
												<h:inputText type="email"
													value="#{usuarioBean.confirmasenha}"
													rendered="#{!usuarioBean.somentePesquisa}"
													class="form-control" id="inputConfirmaSenha1" />
											</div>
										</div>
										<div class="control-group">
											<div class="controls">
												<h:selectBooleanCheckbox
													value="#{usuarioBean.usuario.ativo}"
													readonly="#{usuarioBean.somentePesquisa}" />
												Usuário Ativo
												<h:selectBooleanCheckbox
													value="#{usuarioBean.administrador}"
													readonly="#{usuarioBean.somentePesquisa}"
													id="isAdministrador" />
												Usuário Administrador
											</div>
										</div>
										<div class="control-group">
											<label></label>
											<div class="controls">
												<h:commandButton action="#{usuarioBean.salvar}"
													rendered="#{!usuarioBean.somentePesquisa}"
													class="btn btn-primary btn-block" value="Cadastrar">
													<f:setPropertyActionListener value="/admin/usuarios"
														target="#{usuarioBean.destinosalvar}"></f:setPropertyActionListener>
												</h:commandButton>
											</div>
										</div>
									</h:form>


								</div>
								<!--/panel content-->
							</div>
							<!--/panel-->

						</h:form>

					</div>
				</div>
				<!--/row-->
			</div>
			<!--/col-span-9-->

		</div>
		<!--/row-->
		<!-- /upper section -->
		<footer>
		<p>
			<i class="fa fa-copyright"></i> Guilherme Scha Vieira - 2015
		</p>
		</footer>

	</div>
	<!--/container-->
	<!-- /Main -->

	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="../resources/js/bootstrap.min.js"></script>
</h:body>
</html>